name: flutter_lints_ymadd
description: An extended lint rule set for better coding.
version: 1.0.0
homepage: https://github.com/ymadd/flutter_lints_ymadd

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_lints: ^1.0.4
